dask_cluster_kwargs:
  account: m4632
  queue_name: premium
  n_nodes: 1
  n_tasks_per_node: 128
  wallclock: 06:00:00
  scheduler_file: null

notebooks:
  - title: Ocean CDR Atlas Datasets
    name: ocean-cdr-atlas-datasets
    description: "Download the Ocean CDR Atlas datasets"
    use_dask_cluster: false
    children:
    - notebooks/download-oae-atlas.ipynb:
      parameters:
        injection_year: 1999
        injection_month: 1
        n_test: null
      output_path: executed/ocean-cdr-atlas-datasets/download-oae-atlas.ipynb
  
  - title: Domain Sizing
    use_dask_cluster: true
    name: domain-sizing
    description: "Determine the regions of a finite domain where CDR interventions can be captured by the ocean model."
    children:       
    - notebooks/regional-domain-sizing.ipynb:
      parameters:
        domain_name: "CCS 12km"
        grid_yaml: blueprints/cson_roms-marbl_v0.1_ccs-12km/_grid.yml
        injection_year: 1999
        injection_month: 1
        n_test: null
      output_path: executed/domain-sizing/regional-domain-sizing_cson_roms-marbl_v0.1_ccs-12km.ipynb

    - notebooks/regional-domain-sizing.ipynb:
      parameters:
        domain_name: "Gulf Guinea Toy"
        grid_yaml: blueprints/cson_roms-marbl_v0.1_gulf-guinea-toy/_grid.yml
        injection_year: 1999
        injection_month: 1
        n_test: null
      output_path: executed/domain-sizing/regional-domain-sizing_cson_roms-marbl_v0.1_gulf-guinea-toy.ipynb

    - notebooks/regional-domain-sizing.ipynb:
      parameters:
        domain_name: "Hvalfjörður 0"
        grid_yaml: "blueprints/cson_roms-marbl_v0.1_hvalfj\xF6r\xF0ur-0/_grid.yml"
        injection_year: 1999
        injection_month: 1
        n_test: null
      output_path: "executed/domain-sizing/regional-domain-sizing_cson_roms-marbl_v0.1_hvalfj\xF6\
        r\xF0ur-0.ipynb"

    - notebooks/regional-domain-sizing.ipynb:
      parameters:
        domain_name: "WIO Toy"
        grid_yaml: blueprints/cson_roms-marbl_v0.1_wio-toy/_grid.yml
        injection_year: 1999
        injection_month: 1
        n_test: null
      output_path: executed/domain-sizing/regional-domain-sizing_cson_roms-marbl_v0.1_wio-toy.ipynb

  - title: C-SON Skill Assessment
    use_dask_cluster: false
    name: cson-skill-assessment
    description: "C-SON Skill Assessment"
    children:
    - notebooks/skill-assessment-glodap.ipynb:
      parameters:
        domain_name: "CCS 12km"
        model_files: null
      output_path: executed/skill-assessment/skill-assessment-glodap.ipynb